import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";
import StoreProvider from "./context/StoreProvider";
import { ThemeProvider } from "@mui/material/styles";
import { theme } from "../utils/theme/theme";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Flight Ticket Manager",
  icons: '/favico.png',
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
    <html lang="en">
      <StoreProvider>
        <body className={inter.className}>
          <AppRouterCacheProvider>   <ThemeProvider theme={theme}>{children}</ThemeProvider></AppRouterCacheProvider>
        </body>
      </StoreProvider>
    </html>
  );
}
